"""SMM-Sync MCP server — 16 tools for AI agent coordination and context retrieval.

Coordination tools (original 4):
  read_context      — get full project context + coordination state
  claim_file        — atomically claim a file
  release_file      — release a claimed file
  refresh_context   — check if AGENTS.md changed, re-parse if so

Context graph tools (5):
  query_decisions       — search team decisions and architectural knowledge
  add_decision          — record a new team decision in the knowledge graph
  get_project_context   — comprehensive project context from the graph (returns session_token)
  check_constraints     — check if a proposed action violates known constraints
  check_contradictions  — sync new decisions + detect contradictions inline
  resolve_contradiction — resolve or dismiss a contradiction (winner a/b/dismiss + note + REQUIRES confirmation='YES')

Sprint tools (4):
  get_decision_timeline   — chronological history of decisions on a topic
  get_compliance_lineage  — audit trail for a session or specific decision
  add_constraint          — register a non-negotiable project constraint
  complete_session        — close session, summarise decisions captured, list modified files

CaaS tools (3):
  get_path_context    — JIT path-based rule injection for a file being edited
  get_board_items     — read the decision board (.smm/board.json)
  update_board_item   — create/update/move a board item
"""
from __future__ import annotations

import atexit
import hashlib
import json
import logging
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path
from uuid import uuid4

from mcp.server.fastmcp import FastMCP

from smm_sync.config import DASHBOARD_PORT
from smm_sync.coordinator import claim as _coord_claim
from smm_sync.coordinator import is_claimed, release as _coord_release
from smm_sync.ingester import ingest, load_parsed_context
from smm_sync.state import get_current_state, propose, read_events

logger = logging.getLogger(__name__)
mcp = FastMCP("smm-sync")
_smm_dir: Path | None = None
_graph_client = None  # Lazy-initialised GraphClient
_context_loaded: bool = False  # Set to True after get_project_context succeeds
_session_token: str = ""  # UUID generated by get_project_context; tags all decisions this session
_project_hash: str = ""  # SHA-256[:8] of project root path, set in run_server

_SESSION_NOT_INIT_ERROR = {
    "content": [{"type": "text", "text": (
        "⚠️ SESSION NOT INITIALIZED: You must call get_project_context before using "
        "any other Axiom Hub tool. This loads your project's architectural decisions "
        "and checks for unresolved contradictions."
    )}],
    "isError": True,
}


def _is_session_killed(session_id: str) -> bool:
    """Check if this session has been disconnected from the dashboard.

    Args:
        session_id: Session identifier to check.

    Returns:
        True if the session has been killed, False otherwise.
    """
    if not session_id or _smm_dir is None:
        return False
    killed_path = _smm_dir / "killed_sessions.json"
    try:
        killed = json.loads(killed_path.read_text(encoding="utf-8"))
        return session_id in killed.get("sessions", [])
    except Exception:
        return False


_KILLED_MESSAGE = (
    "⚡ This agent session has been disconnected by the dashboard. "
    "Start a new Claude Code session to reconnect."
)

_MANDATORY_PROTOCOL = """\
MANDATORY PROTOCOL — YOU MUST FOLLOW THESE RULES FOR THIS ENTIRE SESSION:

1. EVERY time you choose between two or more alternatives (database, library, framework, auth pattern, API format, caching strategy, concurrency pattern), you MUST call the add_decision tool BEFORE writing the code. Not after. Before.

2. add_decision requires: title (what you chose), description (why, and what you rejected), type (architectural/technical/product/constraint), confidence (0.0-1.0), session_token (from get_project_context).

3. If you write code without calling add_decision for the choice that led to that code, you are violating this project's governance protocol.

4. AFTER completing your implementation, review every file you wrote. For each technical choice you made during coding (config patterns, test strategies, error handling approaches, dependency injection patterns, data seeding strategies), call add_decision retroactively. Implementation decisions matter as much as architectural ones.

5. When your implementation is complete, call complete_session(session_token=<token>) to close the session and confirm all decisions were captured.

Session flow:
  Step 1: get_project_context (load context, returns token)
  Step 2: Capture pre-build decisions via add_decision
  Step 3: After capturing your pre-build decisions but BEFORE writing any code, present unresolved contradictions to the developer and ask if they want to resolve any. Accept no as an answer. Say: 'Before I start coding, there are N unresolved contradictions. Would you like to resolve any? (yes/no)'
  Step 4: If yes, walk through each contradiction. If no, proceed to coding.
  Step 5: complete_session(token) → commit

Example — you are about to use SQLAlchemy for ORM:
→ FIRST call add_decision with title='SQLAlchemy 2.0 for ORM', description='Selected SQLAlchemy over Tortoise ORM and Django ORM for async support and mature ecosystem', type='technical', confidence=0.9, session_token=<token>
→ THEN write the code

This is not optional. This is a project requirement.\
"""


def _get_smm_dir() -> Path:
    """Return the configured .smm directory.

    Returns:
        Path to .smm directory.

    Raises:
        RuntimeError: If run_server() has not been called yet.
    """
    if _smm_dir is None:
        raise RuntimeError("MCP server not initialised. Call run_server(smm_dir) first.")
    return _smm_dir


def _get_agents_md() -> Path:
    """Return path to AGENTS.md (parent of .smm/).

    Returns:
        Path to AGENTS.md file.
    """
    return _get_smm_dir().parent / "AGENTS.md"


# ---------------------------------------------------------------------------
# Architectural violation detection
# ---------------------------------------------------------------------------

# Maps superseded-decision keywords to grep patterns and file extensions.
_KEYWORD_PATTERNS: dict[str, dict] = {
    "sqlite": {"grep": ["sqlite", "sqlite3"], "find": ["*.db", "*.sqlite"]},
    "postgresql": {"grep": ["psycopg2", "postgresql"], "find": []},
    "celery": {"grep": ["celery", "Celery"], "find": []},
    "backgroundtasks": {"grep": ["BackgroundTasks", "background_tasks"], "find": []},
    "api_key": {"grep": ["X-API-Key", "api_key", "drone_secret"], "find": []},
    "jwt": {"grep": ["python-jose", "jwt"], "find": []},
}

_VERIFICATION_PROTOCOL_MSG = (
    "⚠ VERIFICATION PROTOCOL: You are connected to a REAL terminal.\n"
    "THOUGHT ≠ ACTION: Writing 'I checked' in your reasoning does nothing.\n"
    "You MUST execute the actual bash commands to verify compliance.\n"
    "Do NOT state 'All items satisfied' without running the verification "
    "commands and pasting their output."
)


def _extract_keywords(title: str) -> list[str]:
    """Extract recognised technical keywords from a decision title.

    Args:
        title: Decision title to scan (e.g. "SQLite via SQLAlchemy ORM").

    Returns:
        List of lowercase keyword strings that appear in _KEYWORD_PATTERNS.
    """
    words = re.split(r"[\s\-_/]+", title.lower())
    return [w for w in words if w in _KEYWORD_PATTERNS]


def _run_verification(smm_dir: Path) -> list[str]:
    """Scan the codebase for architectural violations from resolved contradictions.

    Reads .smm/contradiction_index.json, finds resolved pairs, extracts
    keywords from SUPERSEDED decision titles, then runs grep/find against
    the project root.  Each subprocess is limited to 5 seconds.

    Skips pairs whose contradiction has already been marked resolved or
    dismissed in contradictions.jsonl (user acknowledged it; don't re-block).

    Args:
        smm_dir: Path to the .smm directory.

    Returns:
        List of human-readable violation strings.  Empty means clean.
    """
    idx_path = smm_dir / "contradiction_index.json"
    if not idx_path.exists():
        return []

    try:
        idx = json.loads(idx_path.read_text(encoding="utf-8"))
    except Exception:
        return []

    resolved_pairs = [p for p in idx.get("pairs", []) if p.get("status") == "resolved"]
    if not resolved_pairs:
        return []

    # Build set of (da, db) pairs already resolved/dismissed in contradictions.jsonl
    _dismissed: set[tuple[str, str]] = set()
    contra_path = smm_dir / "contradictions.jsonl"
    if contra_path.exists():
        try:
            for _ln in contra_path.read_text(encoding="utf-8").splitlines():
                _ln = _ln.strip()
                if not _ln:
                    continue
                try:
                    _c = json.loads(_ln)
                    _status = (_c.get("status") or "").lower()
                    if _status in ("resolved", "dismissed", "ignored"):
                        _da = (_c.get("decision_a", "") or "").lower().strip()
                        _db = (_c.get("decision_b", "") or "").lower().strip()
                        if _da and _db:
                            _dismissed.add(tuple(sorted([_da, _db])))
                except Exception:
                    pass
        except Exception:
            pass

    project_root = str(smm_dir.parent)
    violations: list[str] = []

    for pair in resolved_pairs:
        loser = pair.get("decision_b_title", "")   # superseded decision
        winner = pair.get("decision_a_title", "")  # kept decision
        if not loser:
            continue

        # Skip if this contradiction was already resolved/dismissed by the user.
        _pair_key = tuple(sorted([loser.lower().strip(), winner.lower().strip()]))
        if _pair_key in _dismissed:
            continue

        keywords = _extract_keywords(loser)
        if not keywords:
            continue

        for kw in keywords:
            patterns = _KEYWORD_PATTERNS[kw]

            for grep_pat in patterns.get("grep", []):
                try:
                    result = subprocess.run(
                        ["grep", "-rn", grep_pat, "--include=*.py", project_root],
                        capture_output=True,
                        text=True,
                        timeout=5,
                    )
                    if result.returncode == 0 and result.stdout.strip():
                        for line in result.stdout.strip().splitlines():
                            violations.append(
                                f"Code uses '{grep_pat}' (superseded by '{winner}'): "
                                f"{line.strip()}"
                            )
                except (subprocess.TimeoutExpired, OSError) as e:
                    logger.warning(f"Failed to search for pattern '{grep_pat}': {e}")

            for file_pat in patterns.get("find", []):
                try:
                    result = subprocess.run(
                        ["find", project_root, "-name", file_pat],
                        capture_output=True,
                        text=True,
                        timeout=5,
                    )
                    if result.returncode == 0 and result.stdout.strip():
                        for fpath in result.stdout.strip().splitlines():
                            violations.append(
                                f"File '{fpath}' exists — DELETE it "
                                f"(superseded by '{winner}')"
                            )
                except (subprocess.TimeoutExpired, OSError) as e:
                    logger.warning(f"Failed to find files matching '{file_pat}': {e}")

    return violations


def _build_block_message(violations: list[str]) -> str:
    """Format a BLOCKED error message listing violations and fix commands.

    Args:
        violations: List of violation strings from _run_verification().

    Returns:
        Human-readable blocking message for the agent.
    """
    numbered = "\n".join(f"{i}. {v}" for i, v in enumerate(violations, 1))

    # Derive fix commands: rm for file violations, grep reminder for code violations
    fix_cmds: list[str] = []
    for v in violations:
        if v.startswith("File '") and "DELETE" in v:
            # Extract the file path between quotes
            m = re.search(r"File '([^']+)'", v)
            if m:
                fix_cmds.append(f"rm {shlex.quote(m.group(1))}")
        elif "Code uses '" in v:
            m = re.search(r"Code uses '([^']+)'", v)
            if m:
                cmd = (
                    f"grep -rn {shlex.quote(m.group(1))} --include='*.py' ."
                )
                if cmd not in fix_cmds:
                    fix_cmds.append(cmd)

    fix_section = "\n".join(fix_cmds) if fix_cmds else "Review violations above and remove superseded code."

    return (
        "BLOCKED: Architectural violations detected. You must fix these "
        "BEFORE accessing project context.\n\n"
        f"VIOLATIONS:\n{numbered}\n\n"
        f"COMMANDS TO FIX:\n{fix_section}\n\n"
        "After fixing, call get_project_context again."
    )


@mcp.tool(structured_output=False)
def read_context() -> str:
    """Return current AGENTS.md content plus active coordination state.

    Agents call this at session start to get full project context:
    architectural decisions, active task, claimed files, active sessions.

    Returns:
        Formatted string combining AGENTS.md content with live state.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    smm_dir = _get_smm_dir()
    agents_md = _get_agents_md()

    agents_content = ""
    if agents_md.exists():
        agents_content = agents_md.read_text(encoding="utf-8")
    else:
        agents_content = "(No AGENTS.md found. Run `smm init` first.)"

    state = get_current_state(smm_dir)
    claimed = state.get("claimed_files", {})
    sessions = state.get("active_sessions", {})

    state_lines = ["\n---\n## Coordination State\n"]
    if claimed:
        state_lines.append("### Claimed Files")
        for fp, info in claimed.items():
            task = info.get("task", "")
            task_str = f" — {task}" if task else ""
            state_lines.append(f"- `{fp}` claimed by `{info['session_id']}`{task_str}")
    else:
        state_lines.append("No files currently claimed.")

    if sessions:
        state_lines.append("\n### Active Sessions")
        for sid, info in sessions.items():
            files = info.get("files", [])
            state_lines.append(f"- `{sid}`: {', '.join(files) if files else 'no files claimed'}")

    last_refresh = state.get("last_refresh", "")
    if last_refresh:
        state_lines.append(f"\nLast context refresh: {last_refresh}")

    return agents_content + "\n".join(state_lines)


@mcp.tool(structured_output=False)
def claim_file(filepath: str, session_id: str, task: str = "") -> dict:
    """Atomically claim a file for exclusive editing.

    Uses propose-validate-commit. Agents must call this before editing
    any file to avoid conflicts with other simultaneous sessions.

    Args:
        filepath: Relative path of file to claim.
        session_id: Unique identifier for this agent session.
        task: Optional description of what this agent is doing.

    Returns:
        Dict with keys:
            success (bool): True if claim succeeded.
            conflict (str): Description of conflict if success=False.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    smm_dir = _get_smm_dir()

    if not _coord_claim(smm_dir, filepath, session_id):
        state = get_current_state(smm_dir)
        owner = state.get("claimed_files", {}).get(filepath, {}).get("session_id", "unknown")
        return {"success": False, "conflict": f"{filepath} is already claimed by {owner}"}

    result = propose(smm_dir, "file_claimed", session_id, {"filepath": filepath, "task": task})
    if not result["accepted"]:
        _coord_release(smm_dir, filepath)
        return {"success": False, "conflict": result["reason"]}

    return {"success": True}


@mcp.tool(structured_output=False)
def release_file(filepath: str, session_id: str) -> dict:
    """Release a claimed file.

    Agents call this after completing edits to a file.

    Args:
        filepath: Relative path of file to release.
        session_id: Identifier of the session that claimed the file.

    Returns:
        Dict with keys:
            success (bool): True if release succeeded.
            reason (str): Failure reason if success=False.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    smm_dir = _get_smm_dir()

    result = propose(smm_dir, "file_released", session_id, {"filepath": filepath})
    if not result["accepted"]:
        return {"success": False, "reason": result["reason"]}

    _coord_release(smm_dir, filepath)
    return {"success": True}


@mcp.tool(structured_output=False)
def refresh_context(session_id: str) -> dict:
    """Check if AGENTS.md changed; re-parse if so.

    Agents call this after a git commit lands to pick up context updates.

    Args:
        session_id: Identifier of the calling session.

    Returns:
        Dict with keys:
            changed (bool): True if AGENTS.md was updated.
            context (str): New parsed context summary if changed=True.
            reason (str): Reason for no change if changed=False.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    smm_dir = _get_smm_dir()
    agents_md = _get_agents_md()

    if not agents_md.exists():
        return {"changed": False, "reason": "AGENTS.md not found"}

    content = agents_md.read_text(encoding="utf-8")
    new_hash = hashlib.sha256(content.encode()).hexdigest()

    result = propose(smm_dir, "context_refreshed", session_id, {
        "context_hash": new_hash,
        "agents_md_path": str(agents_md),
    })

    if not result["accepted"]:
        return {"changed": False, "reason": result["reason"]}

    parsed = ingest(smm_dir, agents_md)
    return {
        "changed": True,
        "context": parsed.get("project", "") + "\n\n" + parsed.get("active_task", ""),
    }


async def _check_github_auth() -> bool:
    """Check if GitHub authentication is still valid.

    Returns True if auth is valid, False otherwise. Never raises.
    """
    import os
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        return False
    try:
        from github import Auth, Github
        gh = Github(auth=Auth.Token(token))
        _ = gh.get_user().login
        return True
    except Exception:
        return False


def _get_graph_client():
    """Return (lazily initialise) the GraphClient for the context graph.

    Uses the module-level singleton from context_graph.client for performance:
    eliminates 2-3 second sentence-transformer model reload between MCP calls.

    Returns:
        GraphClient instance, or None if context_graph is unavailable.
    """
    global _graph_client
    if _graph_client is None:
        try:
            from smm_sync.context_graph.client import get_graph_client

            smm_dir = _get_smm_dir()
            graph_dir = smm_dir / "graph"
            _graph_client = get_graph_client(graph_dir=graph_dir)
        except Exception:
            return None
    return _graph_client


def _get_lineage_logger():
    """Return the compliance lineage logger for the current smm_dir.

    Returns:
        LineageLogger instance, or None if unavailable.
    """
    try:
        from smm_sync.compliance.lineage import LineageLogger

        smm_dir = _get_smm_dir()
        log_path = smm_dir / "compliance_lineage.jsonl"
        return LineageLogger(log_path)
    except Exception:
        return None


def _mark_context_loaded() -> None:
    """Mark this session as initialised and create the lock file for Claude Code hook."""
    global _context_loaded
    _context_loaded = True
    if _project_hash:
        lock_path = Path(f"/tmp/smm-session-{_project_hash}.lock")
        lock_path.touch()
        print(f"[smm-sync] session lock created: {lock_path}", file=sys.stderr)


def _time_saved_footer() -> str:
    """Build a one-line time saved footer for MCP tool responses.

    Reads compliance_lineage.jsonl for injection count in the last 7 days.
    Formula: injections × 3.75 min.

    Returns:
        Footer string to append to tool responses.
    """
    try:
        import json as _json
        from datetime import datetime, timedelta, timezone

        smm_dir = _smm_dir
        if smm_dir is None:
            return ""
        lineage_path = smm_dir / "compliance_lineage.jsonl"
        if not lineage_path.exists():
            return ""
        cutoff = datetime.now(timezone.utc) - timedelta(days=7)
        count = 0
        with open(lineage_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = _json.loads(line)
                    if entry.get("event_type") != "context_injection":
                        continue
                    ts_str = entry.get("timestamp", "")
                    if ts_str:
                        ts = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
                        if ts >= cutoff:
                            count += 1
                except Exception:
                    continue
        mins_week = int(count * 3.75)
        h, m = divmod(mins_week, 60)
        week_str = f"~{h}h {m}m" if h > 0 else f"~{m}m"
        return (
            f"\n\n---\n"
            f"⏱ CaaS: saved ~3.75 min · Total this week: {week_str}"
        )
    except Exception:
        return ""


@mcp.tool(structured_output=False)
async def query_decisions(
    query: str,
    project: str = "smm-sync",
    limit: int = 5,
    session_id: str = "",
) -> str:
    """Search team decisions and architectural knowledge.

    Call this when you need to understand WHY something was built a certain way,
    or what constraints exist before making changes.

    Args:
        query: Natural language question about the project.
               e.g. "why did we choose Kuzu?"
               e.g. "what are the constraints on the MCP server?"
               e.g. "what alternatives were considered for file locking?"
        project: Project name (default: smm-sync).
        limit: Max results to return (default: 5).
        session_id: Optional session identifier (used for kill check).

    Returns:
        Formatted string of relevant decisions with rationale.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    if session_id and _is_session_killed(session_id):
        return _KILLED_MESSAGE
    client = _get_graph_client()
    if client is None:
        return "Context graph unavailable. Run `smm seed-graph` to populate it."

    try:
        results = await client.search_context(query=query, project=project, limit=limit)
    except Exception as e:
        return f"Graph search failed: {e}"

    # Log to compliance lineage
    logger = _get_lineage_logger()
    if logger and results:
        logger.log_context_injection(
            query=query,
            decisions_surfaced=[r.title for r in results],
            agent="mcp-client",
            tool_name="query_decisions",
        )

    # Déjà Vu check — zero LLM calls, purely graph similarity
    rejections = await client.check_rejected_alternatives(query=query, project=project)

    if not results and not rejections:
        return f"No relevant decisions found for query: {query!r} in project {project!r}."

    lines = [f"## Decisions relevant to: {query!r}\n"]

    if rejections:
        lines.append("⚠️  DÉJÀ VU WARNING")
        lines.append("=" * 40)
        lines.append(
            "This query resembles previously-rejected alternatives. "
            "Review before proceeding:\n"
        )
        for r in rejections:
            lines.append(f"**Decision:** {r.decision_title}")
            lines.append(f"**Reason rejected:** {r.rationale[:300]}")
            lines.append(f"**Confidence:** {r.confidence:.2f}")
            lines.append("")
        lines.append("=" * 40 + "\n")

    for i, r in enumerate(results, 1):
        lines.append(f"### {i}. {r.title}")
        lines.append(r.content)
        if r.excerpt and r.excerpt != r.content:
            lines.append(f"\n*Excerpt:* {r.excerpt}")
        lines.append("")
    return "\n".join(lines) + _time_saved_footer()


@mcp.tool(structured_output=False)
async def add_decision(
    title: str,
    content: str = "",
    rationale: str = "",
    made_by: str = "",
    project: str = "smm-sync",
    constraints: list[str] = [],
    alternatives: list[str] = [],
    decision_type: str = "technical",
    confidence: float | None = None,
    session_token: str = "",
    # Field aliases — agents often send these instead of the canonical names
    description: str = "",
    type: str = "",
) -> dict:
    """Record an architectural, technical, product, or constraint decision.

    Call whenever choosing between two or more alternatives. Required fields:
    title, description, type, confidence.

    Args:
        title: Short title of the decision.
        content: Full description of what was decided. Alias: description.
        rationale: Why this decision was made.
        made_by: Who made this decision (defaults to 'agent').
        project: Project name (default: smm-sync).
        constraints: Known constraints imposed by this decision.
        alternatives: Alternatives that were considered.
        decision_type: One of 'architectural', 'technical', 'product', 'constraint'. Alias: type.
        confidence: Confidence score (0.0–1.0).
        session_token: Session token from get_project_context. Stored as session_id
                       in decisions.jsonl and compliance_lineage.jsonl.
        description: Alias for content.
        type: Alias for decision_type.

    Returns:
        Dict with keys: success (bool), decision_id (str) or error (str).
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR

    # Resolve field aliases before any validation
    if description and not content:
        content = description
    if type and decision_type == "technical":
        # "technical" is the default; if an explicit alias was provided, prefer it
        decision_type = type
    if not made_by:
        made_by = "agent"

    if confidence is not None and not (0.0 <= confidence <= 1.0):
        return {"success": False, "error": f"Confidence must be between 0.0 and 1.0, got {confidence!r}"}

    import os as _os
    _use_local = not _os.environ.get("ANTHROPIC_API_KEY", "").strip()

    # Kuzu write — optional; lock contention or unavailability must not block JSONL
    decision_id = str(uuid4())  # fallback ID used when Kuzu is unavailable
    client = _get_graph_client()
    if client is None:
        logger.warning("[add_decision] Context graph unavailable, skipping Kuzu write.")
    else:
        try:
            if _use_local:
                decision_id = await client.add_decision_local(
                    title=title,
                    content=content,
                    rationale=rationale,
                    made_by=made_by,
                    project=project,
                    constraints=list(constraints),
                    alternatives=list(alternatives),
                    decision_type=decision_type,
                )
            else:
                decision_id = await client.add_decision(
                    title=title,
                    content=content,
                    rationale=rationale,
                    made_by=made_by,
                    project=project,
                    constraints=list(constraints),
                    alternatives=list(alternatives),
                    decision_type=decision_type,
                )
        except Exception as e:
            logger.warning(f"[add_decision] Kuzu write failed (lock contention?): {e}")

    # JSONL write — critical path; always runs regardless of Kuzu state.
    # Pass smm_dir explicitly — the MCP server CWD is not the project root
    # so relying on _find_smm_dir() walking up from CWD will fail silently.
    try:
        from smm_sync.jsonl_writer import write_decision as _write_decision
        _write_decision({
            "title": title,
            "rationale": rationale or content,
            "type": decision_type,
            "confidence": confidence,
            "alternatives": list(alternatives),
            "constraints": list(constraints),
            "made_by": made_by,
            "project": project,
            "source": "mcp",
            "session_id": session_token or _session_token,
        }, project=project, smm_dir=_get_smm_dir())
    except Exception as _e:
        logger.warning(f"[add_decision] JSONL write failed: {_e}")

    return {"success": True, "decision_id": decision_id}


def _load_decision_rationales(smm_dir: Path) -> dict:
    """Return {title: rationale} from decisions.jsonl for contradiction display."""
    rationale_map: dict = {}
    decisions_path = smm_dir / "decisions.jsonl"
    if not decisions_path.exists():
        return rationale_map
    try:
        for line in decisions_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
                title = d.get("title", "")
                rationale = d.get("rationale", "") or d.get("content", "")
                if title:
                    rationale_map[title] = rationale or ""
            except Exception:
                pass
    except Exception:
        pass
    return rationale_map


def _format_contradiction_lines(active_contras: list, rationale_map: dict) -> list:
    """Format unresolved contradictions with full context and resolve commands."""
    out: list = []
    out.append(f"⚠ UNRESOLVED CONTRADICTIONS ({len(active_contras)}):")
    out.append("")
    for i, ac in enumerate(active_contras, 1):
        da = ac.get("decision_a", "")
        db = ac.get("decision_b", "")
        reason = ac.get("reason", ac.get("explanation", ""))
        cid = ac.get("uuid", ac.get("id", ""))
        rationale_a = rationale_map.get(da, "") or "(no rationale recorded)"
        rationale_b = rationale_map.get(db, "") or "(no rationale recorded)"
        if len(rationale_a) > 120:
            rationale_a = rationale_a[:117] + "..."
        if len(rationale_b) > 120:
            rationale_b = rationale_b[:117] + "..."
        out.append(f"{i}. [ID: {cid}] '{da}' ↔ '{db}'")
        if reason:
            out.append(f"   Reason: {reason}")
        out.append(f"   Option A rationale: {rationale_a}")
        out.append(f"   Option B rationale: {rationale_b}")
        out.append(f"   → resolve_contradiction(id='{cid}', winner='a') — keep {da}")
        out.append(f"   → resolve_contradiction(id='{cid}', winner='b') — keep {db}")
        out.append(f"   → resolve_contradiction(id='{cid}', winner='dismiss') — dismiss this contradiction")
        out.append("")
    out.append("These require DEVELOPER confirmation to resolve. Present the options and ask the developer to confirm before calling resolve_contradiction.")
    out.append("")
    return out


@mcp.tool(structured_output=False)
async def get_project_context(project: str = "smm-sync", session_id: str = "") -> str:
    """CRITICAL: Must be called FIRST before any other tool in every new session.

    Returns active architectural decisions, unresolved contradictions, and
    project configuration.

    Args:
        project: Project name (default: smm-sync).
        session_id: Optional session identifier (used for kill check).

    Returns:
        Structured summary of all project decisions and constraints.
    """
    if session_id and _is_session_killed(session_id):
        return _MANDATORY_PROTOCOL + "\n\n" + _KILLED_MESSAGE + "\n\n--- REMINDER: Call add_decision for EVERY implementation choice this session. ---"

    import json as _json
    from datetime import datetime as _dt, timedelta, timezone as _tz
    smm_dir = _get_smm_dir()

    # Mark session as initialised FIRST so the lock file exists and the
    # PreToolUse hook unblocks the agent.  The agent must be able to proceed
    # and fix violations — permanently blocking it here causes a deadlock.
    _mark_context_loaded()
    global _session_token
    _session_token = str(uuid4())

    # ── Architectural violation check (warning, not hard block) ──────────────
    violations = _run_verification(smm_dir)

    # ── Primary source: decisions.jsonl ──────────────────────────────────────
    _jsonl_path = smm_dir / "decisions.jsonl"
    _jsonl_rows: list[dict] = []
    if _jsonl_path.exists():
        for _raw in _jsonl_path.read_text(encoding="utf-8").splitlines():
            _raw = _raw.strip()
            if _raw:
                try:
                    _jsonl_rows.append(_json.loads(_raw))
                except Exception as e:
                    logger.warning(f"Failed to parse JSONL line '{_raw[:50]}...': {e}")

    # Build decision metadata from JSONL when available, else fall back to Kuzu.
    _type_counts: dict[str, int] = {}
    _decision_meta: list[tuple[str, str, float]] = []  # (title, type, confidence)
    _all_titles: list[str] = []
    _all_rationales: list[tuple[str, str]] = []  # (title, rationale)

    if _jsonl_rows:
        for _jd in _jsonl_rows:
            _dt_val = (_jd.get("type") or "technical").lower()
            _conf = float(_jd.get("confidence") or 0.80)
            _title = _jd.get("title") or ""
            _rat = _jd.get("rationale") or ""
            _type_counts[_dt_val] = _type_counts.get(_dt_val, 0) + 1
            _decision_meta.append((_title, _dt_val, _conf))
            _all_titles.append(_title)
            _all_rationales.append((_title, _rat))
        decisions_count = len(_jsonl_rows)
    else:
        # Fall back to Kuzu
        client = _get_graph_client()
        if client is None:
            return _MANDATORY_PROTOCOL + "\n\nContext graph unavailable. Run `smm seed-graph` or `smm add-decision` first." + "\n\n--- REMINDER: Call add_decision for EVERY implementation choice this session. ---"
        try:
            decisions = await client.get_decisions(project=project)
        except Exception as e:
            return _MANDATORY_PROTOCOL + f"\n\nFailed to retrieve project context: {e}" + "\n\n--- REMINDER: Call add_decision for EVERY implementation choice this session. ---"

        if not decisions:
            return (
                _MANDATORY_PROTOCOL
                + f"\n\nNo decisions found for project {project!r}. "
                "Run `smm seed-graph` to populate the graph, or use `smm add-decision`."
                + "\n\n--- REMINDER: Call add_decision for EVERY implementation choice this session. ---"
            )

        for d in decisions:
            _content = (d.content or "").replace("\\n", "\n")
            _dt_val = "architectural"
            _conf = 0.80
            for _ln in _content.splitlines():
                if _ln.startswith("Decision type:"):
                    _dt_val = _ln.split(":", 1)[1].strip().lower()
                elif _ln.startswith("Confidence:"):
                    try:
                        _conf = float(_ln.split(":", 1)[1].strip())
                    except Exception as e:
                        logger.warning(f"Failed to parse confidence value from line '{_ln}': {e}")
            _type_counts[_dt_val] = _type_counts.get(_dt_val, 0) + 1
            _decision_meta.append((d.title or "", _dt_val, _conf))
            _all_titles.append(d.title or "")
            _rat = getattr(d, "rationale", "") or ""
            _all_rationales.append((d.title or "", _rat))
        decisions_count = len(decisions)

        # Log to compliance lineage (Kuzu path only)
        logger = _get_lineage_logger()
        if logger and decisions:
            logger.log_context_injection(
                query=f"get_project_context:{project}",
                decisions_surfaced=[d.title for d in decisions],
                agent="mcp-client",
                session_id=_session_token,
                tool_name="get_project_context",
            )

    if not _decision_meta:
        return (
            _MANDATORY_PROTOCOL
            + f"\n\nNo decisions found for project {project!r}. "
            "Run `smm seed-graph` to populate the graph, or use `smm add-decision`."
            + "\n\n--- REMINDER: Call add_decision for EVERY implementation choice this session. ---"
        )

    # Read active contradictions from contradictions.jsonl
    active_contras: list[dict] = []
    try:
        contra_path = smm_dir / "contradictions.jsonl"
        if contra_path.exists():
            for _line in contra_path.read_text(encoding="utf-8").splitlines():
                _line = _line.strip()
                if _line:
                    try:
                        _c = _json.loads(_line)
                        if _c.get("status") not in ("resolved", "dismissed", "ignored") and not _c.get("resolved", False):
                            active_contras.append(_c)
                    except Exception as e:
                        logger.warning(f"Failed to parse contradiction line '{_line[:50]}...': {e}")
    except Exception as e:
        logger.warning(f"Failed to read contradictions file: {e}")

    # Header
    _type_summary = ", ".join(f"{v} {k}" for k, v in sorted(_type_counts.items()))
    lines = [
        _MANDATORY_PROTOCOL,
        "",
        "PROJECT CONTEXT:",
        f"{decisions_count} decisions recorded ({_type_summary}). "
        f"{len(active_contras)} active contradiction{'s' if len(active_contras) != 1 else ''}.",
        "",
    ]

    # ACTION REQUIRED — injected before decisions so agents see it first
    action_lines: list[str] = []
    resolution_lines: list[str] = []
    try:
        idx_path = smm_dir / "contradiction_index.json"
        if idx_path.exists():
            idx = _json.loads(idx_path.read_text(encoding="utf-8"))
            cutoff_7 = _dt.now(_tz.utc) - timedelta(days=7)
            cutoff_30 = _dt.now(_tz.utc) - timedelta(days=30)

            for pair in idx.get("pairs", []):
                if pair.get("status") != "resolved":
                    continue
                actioned_str = pair.get("actioned_at", "")
                if not actioned_str:
                    continue
                try:
                    actioned_dt = _dt.fromisoformat(actioned_str.replace("Z", "+00:00"))
                except Exception:
                    continue

                winner = pair.get("decision_a_title", "")
                loser = pair.get("decision_b_title", "")
                note = pair.get("note", "")
                date_str = actioned_str[:10]

                already_done = False
                # Check Kuzu for "Implemented" markers if graph client is available.
                _kuzu_client = _get_graph_client()
                if _kuzu_client is not None:
                    try:
                        impl_rows, _, _ = await _kuzu_client._driver.execute_query(
                            "MATCH (e:Episodic) WHERE e.name STARTS WITH 'Implemented PM resolution' "
                            "RETURN e.name LIMIT 50"
                        )
                        for r in impl_rows:
                            name = r.get("e.name", "") or ""
                            if winner and winner[:30].lower() in name.lower():
                                already_done = True
                                break
                    except Exception as e:
                        logger.warning(f"Failed to query graph for implementation status: {e}")

                if actioned_dt >= cutoff_7 and not already_done:
                    action_lines.append(
                        f"ACTION REQUIRED — PM Resolution ({date_str}):\n"
                        f"  KEEP: '{winner}'\n"
                        f"  SUPERSEDED: '{loser}'\n"
                        + (f"  PM note: {note}\n" if note else "")
                        + f"  Before starting new work:\n"
                        f"  1. Find code that uses '{loser}' and refactor to '{winner}'\n"
                        f"  2. Mark as done: echo '{{\"title\":\"Implemented PM resolution: {winner[:50]}\","
                        f"\"rationale\":\"Replaced {loser[:40]} on {date_str}\","
                        f"\"type\":\"architectural\",\"confidence\":0.95}}' | smm add-decision --local -\n"
                        f"  3. Commit before new feature work"
                    )
                elif actioned_dt >= cutoff_30:
                    resolution_lines.append(
                        f"  ✓ KEEP: '{winner}' — SUPERSEDED: '{loser}' ({date_str})"
                        + (f"\n    Note: {note}" if note else "")
                    )
    except Exception:
        pass  # never block context retrieval on resolution lookup failure

    if action_lines:
        lines.append(_VERIFICATION_PROTOCOL_MSG)
        lines.append("")
        lines.append("ACTION REQUIRED — Implement these PM resolutions:")
        for i, al in enumerate(action_lines, 1):
            lines.append(f"{i}. {al}")
        lines.append("")

    # Architectural violations — shown as warnings (not a hard block)
    if violations:
        lines.append("⚠ ARCHITECTURAL VIOLATIONS DETECTED:")
        lines.append("  The following superseded patterns were found in the codebase.")
        lines.append("  Fix these before starting new feature work:")
        for i, v in enumerate(violations, 1):
            lines.append(f"  {i}. {v}")
        lines.append("")
        # Derive fix commands for the agent
        _fix_cmds = []
        for v in violations:
            if v.startswith("File '") and "DELETE" in v:
                m = re.search(r"File '([^']+)'", v)
                if m:
                    _fix_cmds.append(f"  rm {shlex.quote(m.group(1))}")
            elif "Code uses '" in v:
                m = re.search(r"Code uses '([^']+)'", v)
                if m:
                    cmd = f"  grep -rn {shlex.quote(m.group(1))} --include='*.py' ."
                    if cmd not in _fix_cmds:
                        _fix_cmds.append(cmd)
        if _fix_cmds:
            lines.append("  Suggested fix commands:")
            lines.extend(_fix_cmds)
            lines.append("")

    # Active contradictions section — always show (Design fix)
    if active_contras:
        _rationale_map = _load_decision_rationales(smm_dir)
        lines.extend(_format_contradiction_lines(active_contras, _rationale_map))
    else:
        lines.append("✅ No unresolved contradictions")
        lines.append("")

    # Resolved contradictions (last 30 days)
    if resolution_lines:
        lines.append("RESOLVED CONTRADICTIONS (last 30 days):")
        lines.extend(resolution_lines)
        lines.append("")

    # Recent decisions
    lines.append("RECENT DECISIONS:")
    for i, (title, dtype, conf) in enumerate(_decision_meta[:10], 1):
        lines.append(f"{i}. {title} [{dtype}, {conf:.2f}]")
    if len(_decision_meta) > 10:
        lines.append(f"... and {len(_decision_meta) - 10} more.")
    lines.append("")

    # Full decision list
    lines.append("ALL DECISIONS:")
    for i, (title, rationale) in enumerate(_all_rationales, 1):
        lines.append(f"\n{i}. {title}")
        if rationale:
            lines.append(f"   Rationale: {rationale[:200]}")

    response = "\n".join(lines)

    # Include AGENTS.md content so the agent gets decision capture rules in one call
    agents_md_path = smm_dir.parent / "AGENTS.md"
    if agents_md_path.exists():
        try:
            agents_md_content = agents_md_path.read_text(encoding="utf-8")
            response += f"\n\n--- DECISION CAPTURE PROTOCOL ---\n{agents_md_content}"
        except Exception:
            pass

    # Auth check — warn if GitHub sync is broken (Fix 3)
    github_ok = await _check_github_auth()
    if not github_ok:
        response += (
            "\n\n\u26a0\ufe0f WARNING: GitHub sync is broken. "
            "Context may be stale. "
            "Check GITHUB_TOKEN environment variable."
        )

    # Build developer stop block when unresolved contradictions exist
    _stop_block = ""
    if active_contras:
        _contra_names = "\n".join(
            f"{i}. '{ac.get('decision_a', '')}' \u2194 '{ac.get('decision_b', '')}'"
            for i, ac in enumerate(active_contras, 1)
        )
        _stop_block = (
            f"\n\nI found {len(active_contras)} unresolved"
            f" contradiction{'s' if len(active_contras) != 1 else ''}."
            f" After I capture decisions for your current task, I will ask if you want to resolve them."
            f" You can skip if they are not relevant."
        )

    return (
        response
        + _time_saved_footer()
        + f"\n\n--- SESSION TOKEN: {_session_token} ---"
        + "\n--- Pass this token to every add_decision call (session_token=) and to complete_session when done. ---"
        + _stop_block
        + "\n--- REMINDER: Call add_decision for EVERY implementation choice this session. ---"
    )


@mcp.tool(structured_output=False)
async def check_constraints(
    proposed_action: str,
    project: str = "smm-sync",
    session_id: str = "",
) -> dict:
    """Check if a proposed action violates any known project constraints.

    Call this before making significant architectural changes, adding dependencies,
    or modifying core systems.

    Args:
        proposed_action: What you are about to do.
                        e.g. "replace Kuzu with FalkorDB"
                        e.g. "add LWW CRDT back to state.py"
                        e.g. "expose raw MCP without gateway"
        project: Project name (default: smm-sync).
        session_id: Optional session identifier (used for kill check).

    Returns:
        Dict with keys:
            conflicts (list[str]): Decisions this action directly conflicts with.
            warnings (list[str]): Decisions worth reviewing before proceeding.
            clear (bool): True if no conflicts or warnings found.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    if session_id and _is_session_killed(session_id):
        return {"conflicts": [_KILLED_MESSAGE], "warnings": [], "clear": False}
    client = _get_graph_client()
    if client is None:
        return {
            "conflicts": [],
            "warnings": ["Context graph unavailable — cannot check constraints."],
            "clear": False,
        }

    try:
        # Search for decisions related to the proposed action
        results = await client.search_context(
            query=proposed_action,
            project=project,
            limit=10,
        )
    except Exception as e:
        return {
            "conflicts": [],
            "warnings": [f"Graph search failed: {e}"],
            "clear": False,
        }

    # Log to compliance lineage
    logger = _get_lineage_logger()
    if logger and results:
        logger.log_context_injection(
            query=proposed_action,
            decisions_surfaced=[r.title for r in results],
            agent="mcp-client",
            tool_name="check_constraints",
        )

    # Heuristic: high relevance scores indicate potential conflicts;
    # lower scores are warnings. Graphiti doesn't expose raw scores on
    # basic search so we use content-based keyword matching as a proxy.
    conflict_keywords = [
        "do not", "never", "must not", "rejected", "prohibited",
        "not expose", "not allowed", "not safe", "forbidden",
    ]
    warning_keywords = [
        "constraint", "caution", "warning", "danger", "only",
        "requires", "must", "before", "check",
    ]

    conflicts = []
    warnings = []

    for r in results:
        content_lower = r.content.lower()
        is_conflict = any(kw in content_lower for kw in conflict_keywords)
        is_warning = any(kw in content_lower for kw in warning_keywords)

        summary = r.title or r.content[:80]
        if is_conflict:
            conflicts.append(summary)
        elif is_warning:
            warnings.append(summary)

    # Auth check — warn if GitHub sync is broken (Fix 3)
    github_ok = await _check_github_auth()
    if not github_ok:
        warnings.append(
            "\u26a0\ufe0f WARNING: GitHub sync is broken. "
            "Context may be stale. "
            "Check GITHUB_TOKEN environment variable."
        )

    return {
        "conflicts": conflicts,
        "warnings": warnings,
        "clear": len(conflicts) == 0 and len(warnings) == 0,
    }


@mcp.tool(structured_output=False)
async def get_decision_timeline(
    topic: str,
    project: str = "smm-sync",
) -> str:
    """Get the chronological history of decisions related to a topic.

    Shows how team thinking evolved, including superseded decisions.

    Call this to understand WHY the codebase evolved the way it did.
    Shows the full audit trail including decisions that were later
    reversed or superseded.

    Research basis: EVOKG (MIT CSAIL 2025) — temporal graphs that track
    superseding relationships outperform static graphs by 23.3%.

    Args:
        topic: Natural language topic (e.g. "state management", "database choice").
        project: Project name (default: smm-sync).

    Returns:
        Chronological timeline of all decisions related to the topic,
        with superseded decisions marked but not hidden.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    client = _get_graph_client()
    if client is None:
        return "Context graph unavailable. Run `smm seed-graph` to populate it."

    try:
        timeline = await client.get_decision_timeline(topic=topic, project=project)
    except Exception as e:
        return f"Timeline retrieval failed: {e}"

    if not timeline:
        return f"No decisions found for topic: {topic!r} in project {project!r}."

    lines = [f"## Decision Timeline: {topic!r}\n", f"{len(timeline)} decisions found.\n"]
    for i, entry in enumerate(timeline, 1):
        status = "✅ ACTIVE" if entry.get("valid") else "⚠️  SUPERSEDED"
        ts = entry.get("created_at") or "unknown time"
        lines.append(f"### {i}. [{status}] {entry['title']}")
        lines.append(f"*{ts}*")
        lines.append(entry.get("content", ""))
        if entry.get("superseded_note"):
            lines.append(f"\n> {entry['superseded_note']}")
        lines.append("")

    return "\n".join(lines)


@mcp.tool(structured_output=False)
async def get_compliance_lineage(
    session_id: str | None = None,
    decision_title: str | None = None,
) -> str:
    """Get the compliance audit trail.

    If session_id provided: shows all context that was injected into that
    AI coding session — exactly what the AI knew during that session.

    If decision_title provided: shows all times this decision was surfaced
    to an AI agent — the full injection history.

    Required for EU AI Act compliance and SOC 2 AI governance audits.

    Args:
        session_id: Optional session identifier to filter by.
        decision_title: Optional decision title to filter by.

    Returns:
        Formatted audit trail string.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    logger = _get_lineage_logger()
    if logger is None:
        return "Compliance lineage logger unavailable."

    if session_id:
        entries = logger.get_session_lineage(session_id)
        header = f"## Compliance Lineage for Session: {session_id}"
    elif decision_title:
        entries = logger.get_decision_lineage(decision_title)
        header = f"## Compliance Lineage for Decision: {decision_title!r}"
    else:
        entries = logger.get_all_entries()
        header = "## Compliance Lineage (all entries)"

    if not entries:
        return f"{header}\n\nNo entries found."

    lines = [header, f"\n{len(entries)} entries.\n"]
    for e in entries[:50]:  # Cap at 50 for display
        ts = e.get("timestamp", "")[:19]
        tool = e.get("tool_name") or e.get("event_type", "")
        decisions = e.get("decisions_surfaced", [])
        if decisions:
            lines.append(f"- {ts} | {tool} | surfaced: {', '.join(decisions[:3])}")
        else:
            lines.append(f"- {ts} | {e.get('event_type', '')} | {e.get('decision_title', '')}")

    if len(entries) > 50:
        lines.append(f"\n... and {len(entries) - 50} more entries.")

    return "\n".join(lines)


@mcp.tool(structured_output=False)
async def add_constraint(
    constraint: str,
    scope_keywords: list[str],
    rationale: str,
    project: str = "smm-sync",
) -> dict:
    """Register a non-negotiable project constraint.

    Constraints are different from decisions — they are rules that must never
    be violated and automatically surface in ANY query related to their scope
    keywords.

    Example:
        add_constraint(
            constraint="Never expose raw MCP to enterprise customers",
            scope_keywords=["MCP", "enterprise", "security"],
            rationale="6 fatal security flaws in raw MCP protocol"
        )

    Args:
        constraint: The constraint rule in one clear sentence.
        scope_keywords: Keywords that trigger this constraint to surface.
        rationale: Why this constraint exists.
        project: Project name (default: smm-sync).

    Returns:
        Dict with keys: success (bool), constraint_id (str) or error (str).
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    client = _get_graph_client()
    if client is None:
        return {"success": False, "error": "Context graph unavailable."}

    try:
        constraint_id = await client.add_decision(
            title=f"[CONSTRAINT] {constraint[:80]}",
            content=constraint,
            rationale=rationale,
            made_by="manual-constraint",
            project=project,
            constraints=[constraint],
            alternatives=[],
            decision_type="architectural",
            source_type="manual",
        )
        return {"success": True, "constraint_id": constraint_id}
    except Exception as e:
        return {"success": False, "error": str(e)}


@mcp.tool(structured_output=False)
async def complete_session(session_token: str) -> str:
    """Close the current work session and summarise decisions captured.

    Must be called after all implementation work is done and before committing.
    Verifies how many decisions were tagged with this session_token and lists
    the files modified during the session (from git diff and git ls-files for new untracked files).

    Args:
        session_token: The UUID returned by get_project_context at session start.

    Returns:
        'Session {token} captured {N} decisions across {M} files.
         Review these modified files for missed decisions: [list]'
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    if not session_token:
        return "session_token is required. Pass the token returned by get_project_context."

    smm_dir = _get_smm_dir()
    decisions_path = smm_dir / "decisions.jsonl"

    # Count decisions tagged with this session
    n_decisions = 0
    if decisions_path.exists():
        for _raw in decisions_path.read_text(encoding="utf-8").splitlines():
            _raw = _raw.strip()
            if not _raw:
                continue
            try:
                row = json.loads(_raw)
                if row.get("session_id") == session_token:
                    n_decisions += 1
            except Exception:
                pass

    # Collect modified files from git (staged + unstaged tracked files, plus new untracked files)
    modified_files: set[str] = set()
    try:
        for _git_args in (["git", "diff", "--name-only", "HEAD"],
                          ["git", "diff", "--cached", "--name-only"],
                          ["git", "ls-files", "--others", "--exclude-standard"]):
            _r = subprocess.run(_git_args, capture_output=True, text=True, timeout=10)
            for _f in _r.stdout.strip().splitlines():
                if _f.strip():
                    modified_files.add(_f.strip())
    except Exception:
        pass

    m_files = len(modified_files)
    files_list = sorted(modified_files)

    # Log session close to compliance lineage
    _ll = _get_lineage_logger()
    if _ll:
        _ll.log_context_injection(
            query=f"complete_session:{session_token}",
            decisions_surfaced=[],
            agent="mcp-client",
            session_id=session_token,
            tool_name="complete_session",
        )

    files_str = ", ".join(files_list) if files_list else "none"

    # Fire-and-forget: run contradiction analysis in background so the next
    # session's get_project_context picks up any newly detected contradictions.
    subprocess.Popen(
        ["smm", "check", "--quiet"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        cwd=str(smm_dir.parent),
    )

    return (
        f"Session {session_token} captured {n_decisions} decisions across {m_files} files. "
        f"Review these modified files for missed decisions: [{files_str}]"
    )


def _read_board(smm_dir: Path) -> list[dict]:
    """Read board items from .smm/board.json (stored as {"items": [...]}).

    Args:
        smm_dir: Path to .smm directory.

    Returns:
        List of board item dicts. Returns [] if file missing or malformed.
    """
    board_path = smm_dir / "board.json"
    if not board_path.exists():
        return []
    try:
        data = json.loads(board_path.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        return data.get("items", [])
    except Exception:
        return []


def _write_board(smm_dir: Path, items: list[dict]) -> None:
    """Write board items to .smm/board.json atomically ({"items": [...]}).

    Args:
        smm_dir: Path to .smm directory.
        items: List of board item dicts to persist.
    """
    smm_dir.mkdir(parents=True, exist_ok=True)
    board_path = smm_dir / "board.json"
    tmp = board_path.with_suffix(".tmp")
    tmp.write_text(json.dumps({"items": items}, indent=2), encoding="utf-8")
    tmp.replace(board_path)


@mcp.tool(structured_output=False)
async def get_path_context(
    file_path: str,
    project: str = "smm-sync",
) -> str:
    """Get just-in-time context rules relevant to the file you are about to edit.

    Call this before editing a file to surface constraints and decisions that
    apply specifically to that part of the codebase.

    Args:
        file_path: Relative or absolute path to the file being edited.
                   e.g. "src/smm_sync/mcp_server.py"
        project: Project name (default: smm-sync).

    Returns:
        Formatted string of relevant rules and constraints (up to 3).
        Returns a "no specific rules" message if the graph is empty or unavailable.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    client = _get_graph_client()
    if client is None:
        return "Context graph unavailable."

    results = await client.get_path_context(file_path=file_path, project=project)
    if not results:
        return f"No specific rules found for path: {file_path!r}"

    lines = [f"## JIT Context for `{file_path}`\n"]
    for r in results:
        lines.append(f"**{r.title}**")
        lines.append(r.excerpt or r.content[:300])
        lines.append("")
    return "\n".join(lines)


@mcp.tool(structured_output=False)
async def get_board_items(
    status: str = "",
) -> str:
    """Read the decision board from .smm/board.json.

    The board tracks decisions, tasks, and blockers in a kanban-style layout
    with statuses: backlog, in_progress, done.

    Args:
        status: Optional filter — one of "backlog", "in_progress", "done".
                Empty string returns all items.

    Returns:
        Formatted markdown list of board items.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    smm_dir = _get_smm_dir()
    items = _read_board(smm_dir)
    if not items:
        return "Board is empty. Use `update_board_item` to add items."

    if status and status != "all":
        items = [i for i in items if i.get("status") == status]

    if not items:
        return f"No board items with status: {status!r}"

    lines = ["## Decision Board\n"]
    for item in items:
        st = item.get("status", "backlog")
        icon = {"backlog": "○", "in_progress": "◑", "done": "●"}.get(st, "○")
        lines.append(f"{icon} **{item.get('title', '?')}** [{st}]")
        if item.get("description"):
            lines.append(f"  {item['description'][:200]}")
        lines.append(f"  id: {item.get('id', '?')}")
        lines.append("")
    return "\n".join(lines)


@mcp.tool(structured_output=False)
async def update_board_item(
    title: str = "",
    status: str = "backlog",
    description: str = "",
    item_id: str = "",
) -> dict:
    """Create or update an item on the decision board.

    Board items track active decisions, open questions, and blockers.
    Status flow: backlog → in_progress → done.

    Args:
        title: Short title for the board item.
        status: One of "backlog", "in_progress", "done". Default: backlog.
        description: Optional longer description or acceptance criteria.
        item_id: If provided, update existing item with this id.
                 If empty, create a new item.

    Returns:
        Dict with keys: success (bool), id (str), action ("created" or "updated").
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR
    import uuid
    from datetime import datetime, timezone

    smm_dir = _get_smm_dir()
    items = _read_board(smm_dir)

    if item_id:
        # Update existing
        for item in items:
            if item.get("id") == item_id:
                if title:
                    item["title"] = title
                item["status"] = status
                if description:
                    item["description"] = description
                item["updated_at"] = datetime.now(timezone.utc).isoformat()
                _write_board(smm_dir, items)
                return {"success": True, "id": item_id, "action": "updated"}
        return {"success": False, "error": f"Item {item_id!r} not found."}

    # Create new
    new_id = str(uuid.uuid4())[:8]
    now = datetime.now(timezone.utc).isoformat()
    items.append({
        "id": new_id,
        "title": title,
        "status": status,
        "description": description,
        "created_at": now,
        "updated_at": now,
    })
    _write_board(smm_dir, items)
    return {"success": True, "id": new_id, "action": "created"}


@mcp.tool(structured_output=False)
async def check_contradictions(project: str = "smm-sync") -> dict:
    """Run smm check inline to sync new decisions and detect contradictions.

    Syncs any unprocessed decisions from JSONL into the graph, runs contradiction
    detection, and returns a summary of what was found. This is the same operation
    as running ``smm check`` from the command line.

    Use this after a burst of ``add_decision`` calls to surface conflicts before
    proceeding with implementation.

    Args:
        project: Project name (default: smm-sync).

    Returns:
        Dict with keys:
            synced (int): Number of new decisions synced into the graph.
            contradictions_found (int): Number of new contradictions detected.
            unresolved (list[dict]): Currently unresolved contradictions
                (each has decision_a, decision_b, reason).
            dirty (bool): True if the graph was updated (smm compile should run).
            message (str): Human-readable summary.
    """
    global _context_loaded
    if not _context_loaded:
        return _SESSION_NOT_INIT_ERROR

    import asyncio as _asyncio_cc

    smm_dir = _get_smm_dir()

    # Run smm check in a thread so we don't block the event loop
    loop = _asyncio_cc.get_event_loop()
    proc_result = await loop.run_in_executor(
        None,
        lambda: subprocess.run(
            ["smm", "check", "--quiet"],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=str(smm_dir.parent),
        ),
    )

    dirty = (smm_dir / ".check_dirty").exists()

    # Read unresolved contradictions
    unresolved: list[dict] = []
    _unresolved_full: list[dict] = []
    contra_path = smm_dir / "contradictions.jsonl"
    if contra_path.exists():
        for _ln in contra_path.read_text(encoding="utf-8").splitlines():
            _ln = _ln.strip()
            if not _ln:
                continue
            try:
                _c = json.loads(_ln)
                if _c.get("status") not in ("resolved", "dismissed", "ignored") and not _c.get("resolved"):
                    unresolved.append({
                        "id": _c.get("uuid", _c.get("id", "")),
                        "decision_a": _c.get("decision_a", ""),
                        "decision_b": _c.get("decision_b", ""),
                        "reason": _c.get("reason", ""),
                    })
                    _unresolved_full.append(_c)
            except Exception:
                pass

    if proc_result.returncode != 0:
        return {
            "synced": 0,
            "contradictions_found": 0,
            "unresolved": unresolved,
            "dirty": dirty,
            "message": f"smm check failed: {proc_result.stderr.strip()[:200]}",
        }

    # Parse output to extract counts (best-effort; quiet mode may produce nothing)
    synced = 0
    contra_found = 0
    _out = proc_result.stdout.strip()
    import re as _re_cc
    _m = _re_cc.search(r"Checked (\d+) new decision", _out)
    if _m:
        synced = int(_m.group(1))
    _m2 = _re_cc.search(r"Found (\d+) contradiction", _out)
    if _m2:
        contra_found = int(_m2.group(1))

    if dirty:
        msg = (
            f"Synced {synced} decision(s), found {contra_found} new contradiction(s). "
            f"{len(unresolved)} unresolved total. Graph updated."
        )
    else:
        msg = f"No new decisions to process. {len(unresolved)} unresolved contradiction(s)."

    _rationale_map_cc = _load_decision_rationales(smm_dir)
    _display = (
        "\n".join(_format_contradiction_lines(_unresolved_full, _rationale_map_cc))
        if _unresolved_full else ""
    )

    return {
        "synced": synced,
        "contradictions_found": contra_found,
        "unresolved": unresolved,
        "dirty": dirty,
        "message": msg,
        "display": _display,
    }


@mcp.tool(structured_output=False)
async def resolve_contradiction(
    id: str,
    winner: str,
    note: str = "",
    confirmation: str = "",
) -> str:
    """Resolves a contradiction. REQUIRES explicit developer confirmation. Before calling, you MUST ask the developer which option to keep and have them type YES to confirm. Never auto-resolve based on PRD context alone.

    Flow:
      1. Show the developer the contradiction with both options and rationales.
      2. Ask: 'Which do you want to keep? A, B, or dismiss?'
      3. After they answer, ask: 'To confirm, type YES to proceed.'
      4. Pass their exact typed confirmation as `confirmation`.

    Records the resolution in contradictions.jsonl and writes an audit event
    to compliance_lineage.jsonl with the SHA-256 hash chain.

    Args:
        id: Contradiction UUID (from get_project_context or check_contradictions).
        winner: Which decision wins — 'a' (keep decision_a), 'b' (keep decision_b),
                or 'dismiss' (mark as not a real contradiction, no action taken).
        note: Optional developer comment on why this choice was made.
        confirmation: Must be exactly 'YES' (typed by the developer). Required.

    Returns:
        Confirmation with resolution outcome and 'Resolved N/M contradictions. N remaining.'
    """
    global _context_loaded
    if not _context_loaded:
        return (
            "⚠️ SESSION NOT INITIALIZED: Call get_project_context before resolve_contradiction."
        )

    if confirmation != "YES":
        raise ValueError(
            "Human confirmation required. Ask the developer to type YES to confirm this resolution."
        )

    if winner not in ("a", "b", "dismiss"):
        return f"Invalid winner={winner!r}. Must be 'a', 'b', or 'dismiss'."

    smm_dir = _get_smm_dir()
    contra_path = smm_dir / "contradictions.jsonl"

    if not contra_path.exists():
        return f"No contradictions.jsonl found at {contra_path}."

    # Load all records; find target by UUID
    records: list = []
    target: dict | None = None
    try:
        for _ln in contra_path.read_text(encoding="utf-8").splitlines():
            _ln = _ln.strip()
            if not _ln:
                continue
            try:
                r = json.loads(_ln)
                records.append(r)
                if (r.get("uuid") == id or r.get("id") == id) and target is None:
                    target = r
            except Exception:
                pass
    except Exception as e:
        return f"Failed to read contradictions.jsonl: {e}"

    if target is None:
        return f"Contradiction ID '{id}' not found."

    da = target.get("decision_a", "")
    db = target.get("decision_b", "")

    from datetime import datetime as _dt_rc, timezone as _tz_rc
    now_str = _dt_rc.now(_tz_rc.utc).isoformat()

    # Mutate the target record (it's in `records` by reference)
    if winner == "dismiss":
        target["status"] = "dismissed"
        target["resolved"] = False
        target["dismissed_at"] = now_str
        if note:
            target["dismiss_note"] = note
        event_type = "contradiction_dismissed"
    else:
        winning_title = da if winner == "a" else db
        losing_title = db if winner == "a" else da
        target["status"] = "resolved"
        target["resolved"] = True
        target["resolved_winner"] = winning_title
        target["resolved_at"] = now_str
        if note:
            target["resolution_note"] = note
        event_type = "contradiction_resolved"

    # Rewrite contradictions.jsonl atomically
    try:
        tmp_path = contra_path.with_suffix(".tmp")
        with open(tmp_path, "w", encoding="utf-8") as fh:
            for r in records:
                fh.write(json.dumps(r, ensure_ascii=False) + "\n")
        tmp_path.replace(contra_path)
    except Exception as e:
        return f"Failed to write contradictions.jsonl: {e}"

    # Write compliance_lineage event with hash chain
    try:
        from smm_sync.jsonl_writer import _write_audit_hashed as _wah
        import uuid as _uuid_rc
        lineage_path = smm_dir / "compliance_lineage.jsonl"
        _wah(lineage_path, {
            "entry_id": str(_uuid_rc.uuid4()),
            "timestamp": now_str,
            "event_type": event_type,
            "contradiction_id": id,
            "decision_a": da,
            "decision_b": db,
            "winner": winner,
            "note": note or None,
            "session_token": _session_token or None,
        })
    except Exception as e:
        logger.warning(f"Failed to write compliance lineage for contradiction resolution: {e}")

    # Count remaining unresolved after update
    remaining = sum(
        1 for r in records
        if r.get("status") not in ("resolved", "dismissed", "ignored") and not r.get("resolved")
    )
    total = len(records)
    actioned = total - remaining

    if winner == "dismiss":
        outcome = f"Dismissed: '{da}' ↔ '{db}' — no action taken."
    else:
        outcome = f"Resolved: keeping '{winning_title}', superseding '{losing_title}'."  # type: ignore[possibly-undefined]

    suffix = (
        "\n\nContinue resolving? Call check_contradictions to see the remaining list."
        if remaining > 0 else "\n\n✅ All contradictions resolved."
    )
    return f"{outcome}\nResolved {actioned}/{total} contradictions. {remaining} remaining.{suffix}"


def _configure_mcp_stdio():
    """Redirect all stdout to stderr for MCP stdio mode.

    MCP uses stdout exclusively for JSON-RPC messages.
    Any non-JSON output on stdout corrupts the protocol.
    This must be called before mcp.run().

    After this call:
    - print() goes to stderr (visible in terminal)
    - mcp.run() has clean stdout for JSON-RPC
    - Logging goes to stderr
    """
    import logging
    logging.basicConfig(
        stream=sys.stderr,
        level=logging.WARNING,
        format='%(levelname)s: %(message)s'
    )


def run_server(smm_dir: Path) -> None:
    """Start the MCP server bound to the given .smm directory.

    Also starts the dashboard on the configured port in a background daemon thread so
    the MCP server and dashboard share one Kuzu connection (no file-lock
    contention when CLI writes go through the dashboard HTTP API).

    Runs in foreground (blocking). Prints the transport info on start.

    Args:
        smm_dir: Path to the .smm directory for this project.
    """
    global _smm_dir, _project_hash
    _smm_dir = smm_dir
    _project_hash = hashlib.sha1(str(Path.cwd().resolve()).encode()).hexdigest()[:8]
    # Clean slate: delete any stale lock from a previously killed session.
    Path(f"/tmp/smm-session-{_project_hash}.lock").unlink(missing_ok=True)
    atexit.register(lambda: Path(f"/tmp/smm-session-{_project_hash}.lock").unlink(missing_ok=True))

    # Root-Cause-1 fix: dashboard runs in same process → shares _graph_client
    # singleton → single Kuzu writer → no "Could not set lock on file" errors.
    import threading

    def _start_dashboard() -> None:
        try:
            from smm_sync.dashboard import run_dashboard  # type: ignore[attr-defined]
            run_dashboard(host="127.0.0.1", port=DASHBOARD_PORT)
        except Exception as exc:  # noqa: BLE001
            import sys as _sys
            print(f"[smm-sync] dashboard failed to start: {exc}", file=_sys.stderr)

    threading.Thread(target=_start_dashboard, name="smm-dashboard", daemon=True).start()

    _configure_mcp_stdio()  # MUST be before mcp.run()
    mcp.run()
